### ISSUE TITLE
Install option for openshift

### ISSUE THREAD

**Issue by sferich888** [abrt/retrace-server#161]
With the growth of openshift and Kubernetes it would be good to see this as a central collection tool for application issue seen by openshift logs or core dumps (create at the close or killing) of a pod.

**Comment by xsuchy** [comment]
For retracing you need all RPMs available, which consume a lot of storage. So I am not sure if you really want this. We are now focusing on having FAF in Docker https://abrt.github.io/faf/container/2017/09/20/FAF-in-container/ We are now preparing article how to run it in OpenShift. And to ability to report unpackaged crash (from inside of containers). I do not think we want to focus on *retrace* server (which create tracebacks from coredumps) for OpenShift. I think FAF in OpenShift is now more important.

**Comment by djuarezg** [comment]
I think this would be great to re-evaluate. Since you have FAF instructions for Openshift it would be great to have this one as well. This way you could run all of them in the same project and make FAF retrace against retrace-server, splitting both components. Storage is not a problem IMHO, as you would need it anyway wherever you put your retrace-server.
