### ISSUE TITLE
Retrace has issues processing path names with ":"

### ISSUE THREAD

**Issue by audrabaker** [abrt/retrace-server#361]
Hello,

If I run retrace-server-task create <vmcorefile> from the terminal where the directory path contains ":" this command will fail. Note the "3A" seems to be the hex value of the ascii character for the colon ":".

[2020-08-11 14:57:03] [I] Downloading remote resources
[2020-08-11 14:57:03] [I] Retrieving local file '/cores/exceptions/yank/02706620/127.0.0.1-2020-08-09-01%3A18%3A28/vmcore'
[2020-08-11 14:57:03] [W] File not found
[2020-08-11 14:57:03] [W] No files found in the tarball
[2020-08-11 14:57:03] [I] Analyzing crash data
[2020-08-11 14:57:03] [E] Crash directory does not contain required file 'vmcore'

If I retrace this using the webui, it does not fail:

[2020-08-11 16:56:34] [I] Downloading remote resources
[2020-08-11 16:56:34] [I] Retrieving local file '/cores/exceptions/yank/02706620/127.0.0.1-2020-08-09-01:18:28/vmcore'

Thanks!

**Comment by DaveWysochanskiRH** [comment]
Confirm this is reproducible on any /var/crash type path with a ':' in it when submitting via "retrace-server-task create".

**Comment by DaveWysochanskiRH** [comment]
Unfortunately this does not fix the problem but I get this:
~~~
$ retrace-server-task create /tmp/127.0.0.1-2020-08-09-011828.tar.gz 
Status code 500 was returned with message: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 root@localhost to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
'
~~~

Log shows
~~~
tail /var/log/httpd/ssl_error_log | cut -d\  -f12-
Traceback (most recent call last):
  File "/usr/share/retrace-server/manager.wsgi", line 456, in application
    backtracewindow = "<h2>Log:</h2><textarea class=\\"backtrace\\">%s</textarea>" % task.get_log()
  File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 1171, in get_log
    return self.get(RetraceTask.LOG_FILE, maxlen=1 << 22)
  File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 1082, in get
    result = f.read(maxlen)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 159: ordinal not in range(128)
~~~

**Comment by DaveWysochanskiRH** [comment]
A simpler path submission does not Traceback but still fails to find the file:
~~~
$ ls -lh /tmp/127.0.0.1-2020-08-09-01\:18\:28/vmcore
-rwxrwxr--+ 2 foo foo 534M Aug  8 12:18 /tmp/127.0.0.1-2020-08-09-01:18:28/vmcore
$ retrace-server-task create /tmp/127.0.0.1-2020-08-09-01\:18\:28/vmcore
~~~

retrace_log shows:
~~~
$ cat /cores/retrace/tasks/401122119/retrace_log 
[2020-08-24 10:54:18] [I] Downloading remote resources
[2020-08-24 10:54:18] [I] Retrieving local file '/tmp/127.0.0.1-2020-08-09-01:18:28/vmcore'
[2020-08-24 10:54:18] [W] File not found
[2020-08-24 10:54:18] [W] No files found in the tarball
[2020-08-24 10:54:18] [I] Analyzing crash data
[2020-08-24 10:54:18] [E] Crash directory does not contain required file 'vmcore'
~~~

**Comment by mgrabovsky** [comment]
@DaveWysochanskiRH Hm, strange, colons seemed to work fine for me. I'll see if I forgot something. What are those characters in the first path, by the way?

**Comment by DaveWysochanskiRH** [comment]
> @DaveWysochanskiRH Hm, strange, colons seemed to work fine for me. I'll see if I forgot something. What are those characters in the first path, by the way?

@mgrabovsky how did you test it?  With "retrace-server-task create" and a path to the vmcore or something else?

The first instance does look strange and to be honest I'm not sure why the tarball has characters that seem to outside ascii range. However, notice the backtrace is because retrace-server is trying to display the 'log' and that code does not handle characters outside ascii range.  I think that's a separate bug, because I've also seen this backtrace in another instance on our production machine where people just forget a leading '/' on a path to a file.  Try this test - leave out the first '/' on a path to a file and submit from the manager page "Custom core location:", i.e.:
~~~
$ ls -lh /cores/exceptions/dwysocha/vmcore-test.bin
-rwxrwxr-- 1 dwysocha dwysocha 534M Aug 24 11:50 /cores/exceptions/dwysocha/vmcore-test.bin
~~~
Now from "Custom core location" put in: cores/exceptions/dwysocha/vmcore-test.bin

I get the same Traceback trying to display the log file as with these strange characters.  This seems to be somehow because 'wget' or something puts weird characters into the log file for the error.  So maybe we need to handle that in a separate issue?
~~~
$ cat /cores/retrace/tasks/497308754/retrace_log 
[2020-08-24 11:51:54] [I] Downloading remote resources
[2020-08-24 11:51:54] [I] Retrieving remote file 'cores/exceptions/dwysocha/vmcore-test.bin'
[2020-08-24 11:51:54] [W] wget exited with 4: wget: unable to resolve host address ‘cores’

[2020-08-24 11:51:54] [W] No files found in the tarball
[2020-08-24 11:51:54] [I] Analyzing crash data
[2020-08-24 11:51:54] [E] Crash directory does not contain required file 'vmcore'
$ tail /var/log/httpd/ssl_error_log | cut -d\  -f12-
Traceback (most recent call last):
  File "/usr/share/retrace-server/manager.wsgi", line 456, in application
    backtracewindow = "<h2>Log:</h2><textarea class=\\"backtrace\\">%s</textarea>" % task.get_log()
  File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 1171, in get_log
    return self.get(RetraceTask.LOG_FILE, maxlen=1 << 22)
  File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 1082, in get
    result = f.read(maxlen)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 231: ordinal not in range(128)
$  dc --expression="10 i 16 o 231 f"
E7
$ hexdump -C /cores/retrace/tasks/497308754/retrace_log
00000000  5b 32 30 32 30 2d 30 38  2d 32 34 20 31 31 3a 35  |[2020-08-24 11:5|
00000010  31 3a 35 34 5d 20 5b 49  5d 20 44 6f 77 6e 6c 6f  |1:54] [I] Downlo|
00000020  61 64 69 6e 67 20 72 65  6d 6f 74 65 20 72 65 73  |ading remote res|
00000030  6f 75 72 63 65 73 0a 5b  32 30 32 30 2d 30 38 2d  |ources.[2020-08-|
00000040  32 34 20 31 31 3a 35 31  3a 35 34 5d 20 5b 49 5d  |24 11:51:54] [I]|
00000050  20 52 65 74 72 69 65 76  69 6e 67 20 72 65 6d 6f  | Retrieving remo|
00000060  74 65 20 66 69 6c 65 20  27 63 6f 72 65 73 2f 65  |te file 'cores/e|
00000070  78 63 65 70 74 69 6f 6e  73 2f 64 77 79 73 6f 63  |xceptions/dwysoc|
00000080  68 61 2f 76 6d 63 6f 72  65 2d 74 65 73 74 2e 62  |ha/vmcore-test.b|
00000090  69 6e 27 0a 5b 32 30 32  30 2d 30 38 2d 32 34 20  |in'.[2020-08-24 |
000000a0  31 31 3a 35 31 3a 35 34  5d 20 5b 57 5d 20 77 67  |11:51:54] [W] wg|
000000b0  65 74 20 65 78 69 74 65  64 20 77 69 74 68 20 34  |et exited with 4|
000000c0  3a 20 77 67 65 74 3a 20  75 6e 61 62 6c 65 20 74  |: wget: unable t|
000000d0  6f 20 72 65 73 6f 6c 76  65 20 68 6f 73 74 20 61  |o resolve host a|
000000e0  64 64 72 65 73 73 20 e2  80 98 63 6f 72 65 73 e2  |ddress ...cores.|
000000f0  80 99 0a 0a 5b 32 30 32  30 2d 30 38 2d 32 34 20  |....[2020-08-24 |
00000100  31 31 3a 35 31 3a 35 34  5d 20 5b 57 5d 20 4e 6f  |11:51:54] [W] No|
00000110  20 66 69 6c 65 73 20 66  6f 75 6e 64 20 69 6e 20  | files found in |
00000120  74 68 65 20 74 61 72 62  61 6c 6c 0a 5b 32 30 32  |the tarball.[202|
00000130  30 2d 30 38 2d 32 34 20  31 31 3a 35 31 3a 35 34  |0-08-24 11:51:54|
00000140  5d 20 5b 49 5d 20 41 6e  61 6c 79 7a 69 6e 67 20  |] [I] Analyzing |
00000150  63 72 61 73 68 20 64 61  74 61 0a 5b 32 30 32 30  |crash data.[2020|
00000160  2d 30 38 2d 32 34 20 31  31 3a 35 31 3a 35 34 5d  |-08-24 11:51:54]|
00000170  20 5b 45 5d 20 43 72 61  73 68 20 64 69 72 65 63  | [E] Crash direc|
00000180  74 6f 72 79 20 64 6f 65  73 20 6e 6f 74 20 63 6f  |tory does not co|
00000190  6e 74 61 69 6e 20 72 65  71 75 69 72 65 64 20 66  |ntain required f|
000001a0  69 6c 65 20 27 76 6d 63  6f 72 65 27 0a           |ile 'vmcore'.|
000001ad

~~~

**Comment by DaveWysochanskiRH** [comment]
Even without the special characters in the tarball, the second instance shows it does not find the file even with a simple escaped ':' path which I would say is probably "the norm" for how someone would submit this.

**Comment by DaveWysochanskiRH** [comment]
> @DaveWysochanskiRH Hm, strange, colons seemed to work fine for me. I'll see if I forgot something. What are those characters in the first path, by the way?

Ok so this must be a double byte character since it is from a case from Asia.  As it turns out, the submission actually does work with the tarball - it just throws a backtrace displaying the log file.  This unfortunately happens from time to time.  I would say it's of course lower priority but if we can handle it that would be good, maybe in a different issue?

I think somehow my testing was flawed in the other one but right now I do not know why.  In any case, I tried a full path to the vmcore with the escaped ':'s and it worked.

**Comment by DaveWysochanskiRH** [comment]
I submitted https://github.com/abrt/retrace-server/issues/364 for the log problem.
