### ISSUE TITLE
remove the dependency on mock

### ISSUE THREAD

**Issue by mozeq** [abrt/retrace-server#5]
Opened '20110701T11:32:05' by jmoskovc as https://fedorahosted.org/abrt/ticket/311

**Comment by xsuchy** [comment]
any reason for this?

**Comment by DaveWysochanskiRH** [comment]
I can't say of the original request but I know of some history of security issues as described in this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1079126
Also, we still cannot use interactive mode on userspace cores due to issues with mock needing to run as root.  For details, see https://bugzilla.redhat.com/show_bug.cgi?id=1292556#c8 which seemingly has been blocked for more than a year.
As far as kernel cores, we avoid mock entirely in all cases.  For x86, we "solved" the 32-bit problem by installing 32-bit crash alongside 64-bit crash, and running that if a 32-bit x86 vmcore is detected.
There has been some POC implementations of userspace cores with docker too, so this bug was also filed to factor out mock if possible
https://bugzilla.redhat.com/show_bug.cgi?id=1321035
I cannot say what is the best way forward at this point.  It looks like there is some developments in but 1079126 but it's unclear if the userspace interactive mode https://bugzilla.redhat.com/show_bug.cgi?id=1264005 can get fixed easily or not.

**Comment by xsuchy** [comment]
This is done. We use podman directly nowadays.
